### ISSUE TITLE
not able to pull dovecot and postfix

### ISSUE THREAD

**Issue by boekhorstb1** [maintaina/containers#19]
I am not able to download the following images because of a permission error:

````
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required"
    }
  ]
}
````

which I get from here: https://ghcr.io/v2/maintaina/containers/dovecot-horde/manifests/latest
and here:  https://ghcr.io/v2/maintaina/containers/postfix-horde/manifests/latest

Thats what docker is complaining about :). Do you know if I overlooked something or might there be a bug @ralflang ? I logged into ghcr.io with  docker and a github token that has all repo scope and and also write and read:packages

**Comment by boekhorstb1** [comment]
sorry, chache or something

**Comment by ralflang** [comment]
try docker login ghcr.io
